name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Clone the repo
      run: |
        git clone -b master --recurse-submodules https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git reset --hard 6a7db34
    - name: Make picoprom folder and copy important files
      run: |
        mkdir -p "${{ github.workspace }}/../picoprom"
        cp ~/pico-sdk/external/pico_sdk_import.cmake "${{ github.workspace }}/../picoprom/"
    - name: Build for pico 1
      env:
        PICO_SDK_PATH: ~/pico-sdk
      


