name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Clone repo to ~/tools/pico-sdk
      run: git clone -b master --recurse-submodules https://github.com/raspberrypi/pico-sdk.git ~/tools/pico-sdk

    - name: Make picoprom folder and copy important files
      run: |
        mkdir -p "${{ github.workspace }}/../picoprom"
        cp ~/tools/pico-sdk/external/pico_sdk_import.cmake "${{ github.workspace }}/../picoprom/"

    - name: Build for pico 1
      env:
        PICO_SDK_PATH: ~/tools/pico-sdk
      run: |
        mkdir -p build && cd build
        cmake .. -DPICO_BOARD={BOARD}
        make

# need to add release

